### ISSUE TITLE
Issue while creating customMandatoryFields

### ISSUE THREAD

**Issue by AhanaAmbshri** [snyk-tech-services/jira-tickets-for-new-vulns#105]
Hi,

I am trying to add our custom Jira field called "Line of Business" in the jira.yaml file but not sure how to do it. I have tried all the below methods, but everything gave me the same error (except the last one):
```
2022/03/27 15:47:23 *** INFO *** Please check that all expected fields are present in the config file
2022/03/27 15:47:23 *** INFO *** Details : {"error":"Field 'value' cannot be set. It is not on the appropriate screen, or unknown., Field 'key' cannot be set. It is not on the appropriate screen, or unknown."}
2022/03/27 15:47:23 *** ERROR *** Request failed
```

1. Jira.yaml
```
  customMandatoryFields:
        key: 
            Value: Security Team
        transition: 
            id: 12345 <- this is the id of the field in jira
```

2. Jira.yaml 
```
  customMandatoryFields:
    key: "Line of Business"
    value: "Security Team"
```
3. Jira.yaml 
```
  customMandatoryFields:
        12345: 
            Value: Security Team
```

4. Jira.yaml

```
  customMandatoryFields:
        components: [{"Line of Business": Security Ratings}]
```
Error
```
2022/03/27 16:18:04 *** ERROR *** Could not Marshalled new ticket, mandatory fields will no the added json: unsupported type: map[interface {}]interface {}
2022/03/27 16:18:04 *** INFO *** Request on endpoint 'https://snyk.io/api/v1/org/orgID/project/projectid/issue/issueid/jira-issue' failed with error 422 Unprocessable Entity
```

Can you please help me with it?
